### ISSUE TITLE
not enough arguments in ocicni.go

### ISSUE THREAD

**Issue by nicolasStevenin** [cri-o/ocicni#25]
Hi,

When i test your project, it fails xith

   **command: go test -buildmode pie -compiler gc -ldflags "-X github.com/cri-o/ocicni/version=0.1.0 -extldflags '-Wl,-z,relro**  '"
   testing: github.com/cri-o/ocicni
github.com/cri-o/ocicni/pkg/ocicni
# github.com/cri-o/ocicni/pkg/ocicni [github.com/cri-o/ocicni/pkg/ocicni.test]
./ocicni.go:503:35: not enough arguments in call to cninet.AddNetworkList
        have (*libcni.NetworkConfigList, *libcni.RuntimeConf)
        want (context.Context, *libcni.NetworkConfigList, *libcni.RuntimeConf)
./ocicni.go:521:29: not enough arguments in call to cninet.DelNetworkList
        have (*libcni.NetworkConfigList, *libcni.RuntimeConf)
        want (context.Context, *libcni.NetworkConfigList, *libcni.RuntimeConf)
./ocicni_test.go:327:25: cannot use fake (type *fakeExec) as type invoke.Exec in argument to initCNI:
        *fakeExec does not implement invoke.Exec (wrong type for ExecPlugin method)
                have ExecPlugin(string, []byte, []string) ([]byte, error)
                want ExecPlugin(context.Context, string, []byte, []string) ([]byte, error)
./ocicni_test.go:400:25: cannot use fake (type *fakeExec) as type invoke.Exec in argument to initCNI:
        *fakeExec does not implement invoke.Exec (wrong type for ExecPlugin method)
                have ExecPlugin(string, []byte, []string) ([]byte, error)
                want ExecPlugin(context.Context, string, []byte, []string) ([]byte, error)
FAIL    github.com/cri-o/ocicni/pkg/ocicni [build failed]

Thanks

**Comment by dcbw** [comment]
I believe this is fixed, ocicni has been updated to work with the CNI release that uses contexts.
