### ISSUE TITLE
Consider moving this project into CRI-O

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/ocicni#37]
I'm not sure if this makes sense but do we want to move this project into CRI-O? We would benefit by a lots of other things, like outdated dependency checks, go modules, linters, unit tests and versioning. Is the project used somewhere else which we would break up when moving it into CRI-O? WDYT?

**Comment by haircommander** [comment]
Yeah this is also used in libpod. So we could think about moving it there instead in anticipation of the libpod integration?

**Comment by saschagrunert** [comment]
Hm yeah, I was not sure if it's worth the effort for a dedicated release engineering.

**Comment by vrothberg** [comment]
libpod seems like a good place 👍 @mheon WDYT?

**Comment by mheon** [comment]
Throwing it in `pkg/ocicni` in libpod SGTM

**Comment by haircommander** [comment]
@mrunalp @dcbw WDYT

**Comment by kwilczynski** [comment]
@cri-o/ocicni-maintainers, do we still want to move this project to become a package under libpod?

**Comment by saschagrunert** [comment]
@kwilczynski I don't think so, we're moving away from libpod in CRI-O so let's close it for now.
