### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by mrunalp** [cri-o/ocicni#7]
I think we could tag a release (maybe 0.1?). 
@dcbw @rajatchopra wdyt?

**Comment by saschagrunert** [comment]
It would be awesome to see semver releases here. It would cleanup the go modules in cri-o. :) WDYT?

**Comment by haircommander** [comment]
v0.1.0 is cut, are we good to close this @mrunalp

**Comment by onlyjob** [comment]
It would be great to tag a new release (please!), to incorporate update of `containernetworking/cni` as well as other changes...

Thanks.

**Comment by kwilczynski** [comment]
@cri-o/ocicni-maintainers, I believe we should be OK with closing this issue already.

There have been multiple releases since it was created.
