### ISSUE TITLE
New release compatible with CNI v1.0

### ISSUE THREAD

**Issue by albertvaka** [cri-o/ocicni#98]
Is there a new release planned that would include https://github.com/cri-o/ocicni/pull/90 for compatibility with CNI 1.0?

**Comment by saschagrunert** [comment]
Hey @albertvaka, not right now but we would have to cut one :) 

cc @mheon @mrunalp @haircommander

**Comment by saschagrunert** [comment]
Created a new release https://github.com/cri-o/ocicni/releases/tag/v0.3.0
